### ISSUE TITLE
nothing happening, no darkchat.cfg file

### ISSUE THREAD

**Issue by harrierjack** [RockyTV/DarkChat#2]
First let me apologize if this is inconvenient or if you dislike messages asking for help. (also if this seems a stupid question, I tried searching the internet, but either my reasoning is wrong or I am trying the wrong keywords, but so far I can't pinpoint the problem)

I've been trying to get the darkchat addon working with DMP server, however so far without success.
(Linux OS and DMP server running with mono).

In the DMPServer directory within plugins I have the darkchat directory with your files: darkchat.cs, darkchat.csproj and another directory 'properties' with the file assemblyinfo.cs.

However I understand there should be a file generated at first start, called  darkchat.cfg, this doesn't happen, I also tried creating the file manually but still no luck.

The reason I ask for some information is, because it is a bit unclear at the moment what dependencies it requires, there is mention of Newtonsoft's JSON.NET and SirCmpwn's ChatSharp, however I can not find much related to chatsharp in the code, nor did I find anything about newtonsofts JSON.NET, I did read one of the commit notes which mentioned no more distribution for JSON so I think I managed to install that manually, however chatsharp still eludes me.

Going through the code, looking for clues, I did find these references in darkchat.csproj, pointing to what seems directories that are not present on my system, but this could also be some compilation file I'm not sure:
  `<Reference Include="ChatSharp">
      <HintPath>..\..\ChatSharp\ChatSharp\bin\Debug\ChatSharp.dll</HintPath>
    </Reference>
    <Reference Include="DarkMultiPlayer-Common">
      <HintPath>..\..\DarkMultiPlayer\Server\bin\Debug\DarkMultiPlayer-Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DMPServer">
      <HintPath>..\..\DarkMultiPlayer\Server\bin\Debug\DMPServer.exe</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MessageWriter2">
      <HintPath>..\..\DarkMultiPlayer\Server\bin\Debug\MessageWriter2.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\Visual Studio 2013\References\JSON\Net40\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>`

Again i'm sorry if this is an inconvenience, I would appreciate any help or anything that could  point me in the right direction.

Thanks

**Comment by RockyTV** [comment]
Hey. No need to apologize, I will try to help out people when they need help.

Your installation is wrong, what you've "installed" is the actual plugin source code. You don't need the source code unless you are doing a custom compile (change features, etc). What you need is the release one, which is already compiled. You can grab it from here: https://github.com/RockyTV/DarkChat/releases

I'm sorry if I didn't made it clear on how to install the plugin. I'm updating the readme.

Thanks!

**Comment by harrierjack** [comment]
DOH :)
That'll probably work a lot better, thanks for making me feel like an idiot :) (when is it ever not a pebkac problem? :P) 

It is loading the plugin now, it still wont create the .cfg file though. It gives this error in DMP: 

[15:24:28][ERROR] : Cannot activate plugin DarkChat, Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at DarkMultiPlayerServer.DMPPluginHandler.CurrentDomain_AssemblyResolve (System.Object sender, System.ResolveEventArgs args) [0x00000] in <filename unknown>:0 
  at System.AppDomain.DoAssemblyResolve (System.String name, Boolean refonly) [0x00000] in <filename unknown>:0 
  at DarkChat.DarkChat..ctor () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, Boolean nonPublic) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <filename unknown>:0 
  at DarkMultiPlayerServer.DMPPluginHandler.ActivatePluginType (System.Type loadedType) [0x00000] in <filename unknown>:0 


What am I missing, somthing DMP related? Or still not all mono/Json components installed?

Thanks for the help, and fast response

**Comment by RockyTV** [comment]
Uhm.. I have no clue on that one :P. Can you share a screenshot of the Plugins folder? 

And also, next time you're going to send server logs, upload them to [Pastebin](http://pastebin.com). It keeps the comment clean.

**Comment by harrierjack** [comment]
sorry about that, I'll see what I can do.

tried DMPServer/Plugins/ and DMPServer/Plugins/DarkChat

both load the plugin and give exactly the same error :S

**Comment by RockyTV** [comment]
It might be an issue with the JSON version. I'm in a kind of a hurry, but I'll see if I can get it to work with the newest JSON.Net release.

I plan on abandoning JSON config files, and using my own library instead.

**Comment by harrierjack** [comment]
Take your time, I'll see what I can find meanwhile.
What version are you saying it should work with?

**Comment by RockyTV** [comment]
Try the newest release I just drafted. It contains both ChatSharp and JSON.Net in it.

**Comment by harrierjack** [comment]
Yes that did it, copied the ChatSharp.dll and Newtonsoft.dll in the Plugins/DarkChat folder, all green server text :)

.cfg file is present and it connected to your default irc server.

Thanks a bunch for the swift solution. 
Can't wait to see what KSP's future holds :)

**Comment by harrierjack** [comment]
Well everything loads, connects to channel and is present. But there still might be an issue, (or probably user related), but no text or chat is actually received.

DMP server says 'TCP transmission complete" every now and then, yet no text is received from IRC -> DMP or vice versa.

There aren't many other messages in DMPServer itself other then the TCP transmission received

**Comment by RockyTV** [comment]
Hm... I'll rework the code tomorrow (I think). TCP Transmission Complete messages are from the IRC Library. I'll disable them via code.

You're not seeing the ingame messages in IRC because you only need to send messages in the IRC channel room ingame. When I rework it, I'll add an option to send messages from the global chat to the specified IRC channel.

**Comment by harrierjack** [comment]
aha, now I get it, (sorry if I seem stupid :P )

indeed, joining #\<IRC-channel-name> in KSP did the trick, now all text is visible, and gets sent from KSP-> IRC and back

Not sure if this is made clear somewhere (I know I didnt get it untill now) perhaps a good idea to put it in the instructions somewhere :)

For some reason I figured #global chat would be the default channel but that's probably since that is the only one used on the server
